name: Release to Github

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: release to github with gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI_COMMIT_SHA: ${{ env.GITHUB_SHA }}
      run: ./gradlew githubRelease

